set -g status-style 'fg=#e0def4 bg=#232136'
setw -g window-status-current-style 'fg=#232136 bg=#9ccfd8 nobold'
setw -g window-status-current-format ' #I #W '
setw -g window-status-style 'fg=#6e6a86 bg=#232136'
setw -g window-status-format ' #I #[fg=#e0def4]#W '
set -g pane-border-style 'fg=#393552'
set -g pane-active-border-style 'fg=#9ccfd8'